name: flask-packager
version: 1.0.0
build:
  dependencies:
    # Ruby and Bundler for Packager.io
    - ruby-full
    - bundler
    # Python3 for Flask app
    - python3
    - python3-pip
    - python3-venv
    # Other required tools
    - curl
    - git
    - make
  script:
    # Update package lists (for Debian/Ubuntu-based distros)
    - apt-get update -y || yum update -y
    # Install dependencies for Python and Flask app
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt
    # Set up Ruby and Bundler inside the Packager.io build
    - gem install bundler
    - bundler install
    # Ensure correct permissions
    - chmod +x start.sh
package:
  type: deb
  distro: ubuntu
  distro_version: 22.04
  architecture: amd64
  files:
    - ./* /opt/flask-app/
  script:
    - echo "Package built successfully!"
    - echo "Application is ready for deployment."
