name: flask-packager
version: 1.0.0

build:
  dependencies:
    - ruby3.1.4
    - ruby3.1.4-dev
    - bundler
    - python3
    - python3-pip
    - python3-venv
  script:
    - apt-get update -y || yum update -y
    - apt-get install -y software-properties-common
    - add-apt-repository ppa:brightbox/ruby-ng -y
    - apt-get update -y
    - apt-get install -y ruby3.1.4 ruby3.1.4-dev bundler
    - ruby -v  # Verify Ruby version
    - gem install bundler
    - bundler -v  # Verify Bundler installation
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt
    - chmod +x start.sh

package:
  type: deb
  distro: ubuntu
  distro_version: 22.04
  architecture: amd64
  files:
    - ./* /opt/flask-app/
  script:
    - echo "Package built successfully!"
    - echo "Application is ready for deployment."

buildpack: https://github.com/heroku/heroku-buildpack-python.git
